export const selector = {
    pageHeading: '//img[@alt="Decathlon"]',
    shopCollection: '//a[@href="#shop-sections"]',
    articles: '//h2[normalize-space()="Fleeces"]',
    item1: "//h2[normalize-space()='Fleeces']/following-sibling::div//h3[normalize-space()='Hiking Fleece Jacket - Hood']",
    item2: "//h2[normalize-space()='Fleeces']/following-sibling::div//h3[normalize-space()='Hiking Fleece Vest - MH120']",
    item3: "//h2[normalize-space()='Fleeces']/following-sibling::div//h3[normalize-space()='Reversible Hunting Fleece']",
    itemsBag: '//button[@id="headlessui-popover-button-:rl:"]',
    popupScreen: '//p[normalize-space() = "In stock and ready to ship"]',
    addToBag: '//button[normalize-space()="Add to bag"]',
    openBagButton: '//select[@id="currency"]/following-sibling::div[1]',
    verifyItem1AddedToBag: '(//h3[normalize-space()="Hiking Fleece Jacket - Hood"])[1]',
    verifyItem2AddedToBag: '(//h3[normalize-space()="Hiking Fleece Vest - MH120"])[1]',
    verifyItem3AddedToBag: '(//h3[normalize-space()="Reversible Hunting Fleece"])[1]',
    checkoutButton: '//a[normalize-space()="Checkout"]',
    personalInformation: '//h2[normalize-space() = "Personal Information"]',
    firstName: '//input[@id="first_name"]',
    lastName: '//input[@id="last_name"]',
    phoneNumber: '//input[@id="phone_number"]',
    emailAddress: '//input[@id="email"]',
    nextStep: '(//button[normalize-space()="Next Step"])[1]',
    addressLabel: '//label[@for="address"]',
    inputAddressField: '//input[@id="address"]',
    inputAddressCity: '//input[@id="city"]',
    inputAddressState: '//input[@id="state"]',
    inputAddressPostalCode: '//input[@id="postal_code"]',
    inputShippingMethodHomeDelivery: '//input[@id="delivery"]',
    homeDeliveryCheckBox: '//label[@for="delivery"]',
    paymentLabel: '//h2[normalize-space()="Payment"]',
    cashOnDeliveryCheckbox: '//input[@id="CASH_ON_DELIVERY"]',
    completeOrder: '//a[normalize-space()="Complete Order"]',
    thankYouText: '//h1[normalize-space()="Thank you!"]'
};